apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.17-slim # docker pull nginx:stable-alpine3.17-slim
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
              name: { { .Values.configmap.name } }
          ports:
            - containerPort: 8080
