apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ngnix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serviceName
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
